# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
