# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 07:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_auto_20180908_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Book_requset', models.BooleanField(default=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('is_accept', models.BooleanField(default=False)),
                ('is_reject', models.BooleanField(default=True)),
                ('Name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('MobileNumber', models.IntegerField(default=0)),
                ('PinCode', models.IntegerField(default=0)),
                ('Book_request_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('email', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
            ],
        ),
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
