# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20180909_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_request',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
        ),
    ]
